version: '3'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  janus:
    image: 'canyan/janus-gateway:0.9.2'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./janus/config/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./janus/recordings:/recordings"
    restart: always

  parser:
    image: giordanocardillo/janus-post-processor:latest
    entrypoint: /bin/sh
    command: "-c 'while sleep 3600; do :; done'"
    volumes:
      - ./janus/recordings:/recordings

#  janus-gateway:
#    image: mcroth/docker-janus:latest
#    container_name: janus-gateway
#    volumes:
#      - ./janus/etc/janus/:/opt/janus/etc/janus/
#      - ./janus/recordings:/recordings
#      - ./janus/janus.log:/var/log/janus.log
#    ports:
#      - 8088:8088
#      - 8188:8188
#    networks:
#      - back-tier
#      - front-tier



